//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivraisonRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        internal readonly object Photo;

        public int Id { get; set; }
        public string Reference { get; set; }
        public string Lieu { get; set; }
        public int CategoryId { get; set; }
    }
}
